language: node_js
node_js:
- '10'
- '12'
- '14'
deploy:
  api_key:
    secure: BLK/F12BbXJNLSmR4IvO7zuVl0su/DX4OSOQwnnfFoyJuK/+5tYkTvC8/jm9PZxKGsbchHxSXWQPAiHOJ0DOcOhcJ+8irRyrKrz0QnM+ihXzr4tl3axW7dGHP5hJldL5y69AJjnSe6PLjs4ne5vuvOWETznuPbEO6A2E7S8mKlP/tCRCttdE4yXwCq5oTES4vl3cbQjy7PtytdSNWe6LcMUgj1KdW+KDG3xZQ/DKOYGF9tqxgdmpGWvoKBdPxB7gtTtJMVl+BBBN1HtkF9GqCAaCBotnFrFmmGHqDU3WHhnxJbnfnY5Po7Df8xzgSexbtfQ94WSwQr2G8xox052lD+b9KmwXdlBpxQHWuv/hK7OkTPjHxibInGLK5+P7x0mnAQVhhEEEe7R81fcrCM9DK1NgRWWfHFfXeljLQb8WrK67NSqP4pe5rBGj6b5XmVrK1qcV+R7HxjWmovVRNzY+GoumyhLLErAcwNzGJV9HCIDdf7XSODpQxrYMnhin7MtgvZ11r/LJbg8aKiF4rmkaNv3MdzMDU4ysySNRuDnrTIbx6kZ9BWbF5rRVYobyLUVHiM3AOhV+dDb5XNp5+rhqAlANE0/zn25bEiFLRoV1KCElVXAe9JPGc3T98yEW70g9+Uhk8zaSc5B/3EmJOEkc0lbnXG2diT4a+5SaFv5PQeA=
  email: julian@dotcore.co.il
  provider: npm
  skip_cleanup: true
  on:
    tags: true
script:
- npm run build
- npm test
after_success:
- npm run coveralls
