language: node_js
node_js:
- '4'
- '6'
- '8'
deploy:
  api_key:
    secure: jVeoex7yUxY6g6d73C3XMb2MNMhx1aKNPue7aGvWMDoCojhXhAb412X7Da6ZL25Le77mg+88zCl3wn9kuHfcG+6Wj0bNeaHDoJvgYpwEyJcrijUEpsyvKM7KChWSs4AMVXUxz9dTgzTDwtKU9NuPAnDQvFLHQ409xKSEEjulX3gHI2soPbJ5iCcyqs3UzEDMdAgnSD0uw8T2syGOQXO+S43CXWIE3tXhPIvl7d2q/Ygdxc6/8kRJTlQ6xq5dC9wxvVwnfPUue2Tf4poiQMF+BWTmp3Bm0NfOF9dEbizQ4ggE+rZCMOIj//07pBEW7DkHlCjgf38z6+/Z8y0lw6lxnD6mYjRGqI3vE7asaK/jnUn9prF2AIL0TczuMdFanwQD44DULQPNq0mWbqBPTw3hrcUiV8sRIYHtnsEGJxCZLNbLvPUk/YnPYhCYDzpNzXUEW63p77+b+QWMMifSkblZ91zDmpzqjZs90lpBEdzRtMZsRZ+l+MtsfpX1Jk4dLt3BmAIaeLDOJciBG7yJpupF+HsqKvOpXtT9SXS2fnjAqw09kms7owEUU6LrXk0QKTz0tO+5wOJ+7onvnGi4V+Xb4R+bjQE6c+7z49wrbYElPmJPpPvOCAeD3LiHXZjJfIKfqElZNHXRuVVOUbE9KCeHCpID7b+drKXKbfrdSPw0aOg=
  email: julian@dotcore.co.il
  provider: npm
  on:
    tags: true
script:
- npm test
after_success:
- npm run coveralls
