name: test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
        rollup-version:
          - ^2.0.0
          - ^3.0.0
          - ^4.0.0
        i18next-conv-version:
          - ^14
          - ^15

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Install i18next-conv
        run: npm install --no-save i18next-conv@${{ matrix.i18next-conv-version }}

      - name: Install rollup
        run: npm install --no-save rollup@${{ matrix.rollup-version }}

      - name: Test
        run: npm run cover

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
